### ISSUE TITLE
2048 game in c++

### ISSUE THREAD

**Issue by firoz3130** [niegfg/Hacktoberfest-2022#15]
2048 game, a sliding block puzzle game ,to be built using C++.
Kindly assign this to me under Hacktoberfest 2022.

**Comment by ahmadsohail404** [comment]
assigned

**Comment by firoz3130** [comment]
Created the PR;
please review.

**Comment by firoz3130** [comment]
Created the PR;
please review it and merge it under hacktoberfest label.

**Comment by firoz3130** [comment]
> assigned

Thank you for this.
